#!/bin/zsh
gamma=$1
nu=$2
for i in 1 2 3 4; do
	java -classpath libsvm.jar svm_train -s 1 -g $gamma -n $nu ../../test$i/train.data ../../test$i/trainoutput > /dev/null
	java -classpath libsvm.jar svm_predict ../../test$i/test.data ../../test$i/trainoutput ../../test$i/output
done
correct="$(cat ../../test1/test.data newline ../../test2/test.data newline ../../test3/test.data newline ../../test4/test.data newline | cut -b -1)"
predicted="$(cat ../../test1/output ../../test2/output ../../test3/output ../../test4/output | cut -b -1)"

echo $correct > correctValues
echo $predicted > predictedValues 

