#!/bin/zsh
max=0.0
for gamma in 1.0 0.8 0.5 0.2 0.1 0.08 0.05 0.03 0.01 0.008 0.005 0.003 0.001 0.0008 0.0005 0.0003 0.0001; do	
	for nu in 0.17 0.15 0.12 0.1 0.09 0.08 0.06 0.04 0.02 0.01 0.008 0.005 0.001; do 
		data="$(./checker $gamma $nu)"
		echo $data
		ismax=${data#*nu: * }
		if (( $(echo "$max < $ismax" | bc -l) )); then
			max=$ismax
			maxvalue=$data
		fi 
	done
done

echo ""
echo "Max value found:"
echo $maxvalue
